#ifndef _LMX9838_DEFINITION_H
#define _LMX9838_DEFINITION_H

#define LMX_START_DEL   0x02
#define LMX_STOP_DELL   0x03

///////////////////////Packet Type Identification///////////////////////////////

#define LMX_REQUEST                     0x52
#define LMX_CONFIRM                     0x43
#define LMX_INDICATION                  0x96
#define LMX_RESPONSE                    0x72

////////////////////////////////Opcodes/////////////////////////////////////////

#define LMX_GAP_INQUIRY                 0x00
#define LMX_GAP_DEVICE_FOUND            0x01
#define LMX_GAP_REMOTE_DEVICE_NAME      0x02
#define LMX_GAP_READ_LOCAL_NAME         0x03
#define LMX_GAP_WRITE_LOCAL_NAME        0x04
#define LMX_GAP_READ_LOCAL_BDA          0x05
#define LMX_GAP_SET_SCANMODE            0x06
#define LMX_GAP_GET_FIXED_PIN           0x16
#define LMX_GAP_SET_FIXED_PIN           0x17
#define LMX_GAP_GET_PIN                 0x75
#define LMX_GAP_GET_SECURITY_MODE       0x18
#define LMX_GAP_SET_SECURITY_MODE       0x19
#define LMX_GAP_REMOVE_PAIRING          0x1B
#define LMX_GAP_LIST_PAIRED_DEVICES     0x1C
#define LMX_GAP_ENTER_SNIFF_MODE        0x21
#define LMX_GAP_EXIT_SNIFF_MODE         0x37
#define LMX_GAP_ENTER_PARK_MODE         0x38
#define LMX_GAP_EXIT_PARK_MODE          0x39
#define LMX_GAP_ENTER_HOLD_MODE         0x3A
#define LMX_GAP_SET_LINK_POLICY         0x3B
#define LMX_GAP_GET_LINK_POLICY         0x3C
#define LMX_GAP_POWER_SAVE_MODE_CHANGED 0x3D
#define LMX_GAP_ACL_ESTABLISHED         0x50
#define LMX_GAP_ACL_TERMINATED          0x51
#define LMX_GAP_SET_AUDIO_CONFIG        0x59
#define LMX_GAP_GET_AUDIO_CONFIG        0x5A
#define LMX_GAP_ESTABLISH_SCO_LINK      0x5D
#define LMX_GAP_RELEASE_SCO_LINK        0x5E
#define LMX_GAP_MUTE_MIC                0x5F
#define LMX_GAP_SET_VOLUME              0x60
#define LMX_GAP_GET_VOLUME              0x61
#define LMX_GAP_CHANGE_SCO_PACKET_TYPE  0x62
#define LMX_SPP_SET_PORT_CONFIG         0x07
#define LMX_SPP_GET_PORT_CONFIG         0x08
#define LMX_SPP_PORT_CONFIG_CHANGED     0x09
#define LMX_SPP_ESTABLISH_LINK          0x0A
#define LMX_SPP_LINK_ESTABLISHED        0x0B
#define LMX_SPP_INCOMMING_LINK_ESTABL   0x0C
#define LMX_SPP_RELEASE_LINK            0x0D
#define LMX_SPP_LINK_RELEASED           0x0E
#define LMX_SPP_SEND_DATA               0x0F
#define LMX_SPP_INCOMING_DATA           0x10
#define LMX_SPP_TRANSPARENT_MODE        0x11
#define LMX_SPP_CONNECT_DEFAULT_CON     0x12
#define LMX_SPP_STORE_DEFAULT_CON       0x13
#define LMX_SPP_GET_LIST_DEFAULT_CON    0x14
#define LMX_SPP_DELETE_DEFAULT_CON      0x15
#define LMX_SPP_SET_LINK_TIMEOUT        0x57
#define LMX_SPP_GET_LINK_TIMEOUT        0x58
#define LMX_SPP_PORT_STATUS_CHANGED     0x3E
#define LMX_SPP_GET_PORT_STATUS         0x40
#define LMX_SPP_PORT_SET_DTR            0x41
#define LMX_SPP_PORT_SET_RTS            0x42
#define LMX_SPP_PORT_BREAK              0x43
#define LMX_SPP_PORT_OVERRUN_ERROR      0x44
#define LMX_SPP_PORT_PARITY_ERROR       0x45
#define LMX_SPP_PORT_FRAMING_ERROR      0x46
#define LMX_SDAP_CONNECT                0x32
#define LMX_SDAP_DISCONNECT             0x33
#define LMX_SDAP_CONNECTION_LOST        0x34
#define LMX_SDAP_SERVICE_BROWSE         0x35
#define LMX_SDAP_SERVICE_SEARCH         0x36
#define LMX_SDAP_SERVICE_REQUEST        0x1E
#define LMX_SDAP_ATTRIBUTE_REQUEST      0x3F
#define LMX_CHANGE_LOCAL_BDADDRESS      0x27
#define LMX_CHANGE_NVS_UART_SPEED       0x23
#define LMX_CHANGE_UART_SETTINGS        0x48
#define LMX_SET_PORTS_TO_OPEN           0x22
#define LMX_GET_PORTS_TO_OPEN           0x1F
#define LMX_RESTORE_FACTORY_SETTINGS    0x1A
#define LMX_STORE_CLASS_OF_DEVICE       0x28
#define LMX_FORCE_MASTER_ROLE           0x1D
#define LMX_READ_OPERATION_MODE         0x49
#define LMX_WRITE_OPERATION_MODE        0x4A
#define LMX_SET_DEFAULT_LINK_POLICY     0x4C
#define LMX_GET_DEFAULT_LINK_POLICY     0x4D
#define LMX_SET_EVENT_FILTER            0x4E
#define LMX_GET_EVENT_FILTER            0x4F
#define LMX_SET_DEFAULT_LINK_TIMEOUT    0x55
#define LMX_GET_DEFAULT_LINK_TIMEOUT    0x56
#define LMX_SET_DEFAULT_AUDIO_CONFIG    0x5B
#define LMX_GET_DEFAULT_AUDIO_CONFIG    0x5C
#define LMX_SET_DEFAULT_LINK_LATENCY    0x63
#define LMX_GET_DEFAULT_LINK_LATENCY    0x64
#define LMX_SET_CLOCK_FREQUENCY         0x67
#define LMX_GET_CLOCK_FREQUENCY         0x68
#define LMX_SET_PCM_SLAVE_CONFIG        0x74
#define LMX_ENABLE_SDP_RECORD           0x29
#define LMX_DELETE_SDP_RECORDS          0x2A
#define LMX_STORE_SDP_RECORD            0x31
#define LMX_RESET                       0x26
#define LMX_READY                       0x25
#define LMX_TEST_MODE                   0x24
#define LMX_WRITE_ROM_PATCH             0x47
#define LMX_READ_RSSI                   0x20
#define LMX_RF_TEST_MODE                0x4B
#define LMX_DISABLE_TL                  0x52
#define LMX_TL_ENABLED                  0x53
#define LMX_HCI_COMMAND                 0x65
#define LMX_AWAIT_INITIALIZATION_EVENT  0x66
#define LMX_ENTER_BLUETOOTH_MODE        0x66
#define LMX_SET_CLOCK_AND_BAUDRATE      0x69
#define LMX_SET_GPIO_WPU                0x6B
#define LMX_GET_GPIO_STATE              0x6C
#define LMX_SET_GPIO_DIRECTION          0x6D
#define LMX_SET_GPIO_OUTPUT_HIGH        0x6E
#define LMX_SET_GPIO_OUTPUT_LOW         0x6F
#define LMX_READ_NVS                    0x72
#define LMX_WRITE_NVS                   0x73

#endif	//#ifndef _LMX9838_DEFINITION_H